version: "3.3"
services:
  bonsai:
    image: impworks/bonsai:latest
    restart: unless-stopped
    volumes:
      - images:/app/wwwroot/media
    environment:
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=bonsai;User Id=bonsai;Password=test;Persist Security Info=true
      - ElasticSearch__Host=http://elastic:9200
      - Auth__Facebook__AppId=
      - Auth__Facebook__AppSecret=
      - Auth__Google__ClientId=
      - Auth__Google__ClientSecret=
      - WebServer__RequireHttps=false
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
    stop_signal: SIGKILL
    links:
      - postgres
      - elastic

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: bonsai
      POSTGRES_DB: bonsai

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    entrypoint: >
      bash -c "
      bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.14/elasticsearch-analysis-morphology-5.6.14.zip
      && bin/es-docker"
    networks: 
      public: {}

volumes:
  database: {}
  elastic: {}
  images: {}