# !!! ATTENTION !!!
# Before using this file you will need to replace the following placeholders with actual values:
#
#   @@YOUR_EMAIL@@: your email address (required for LetsEncrypt certificate issuing)
#   @@YOUR_IP@@: the external IP of the webserver on which Bonsai runs

version: "3.3"
services:
  traefik:
    image: traefik:1.5.4
    restart: always
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=true"
      - "--acme.email=@@YOUR_EMAIL@@"
      - "--docker"
      - "--docker.watch"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme:/etc/traefik/acme

  bonsai:
    image: impworks/bonsai:latest
    restart: unless-stopped
    volumes:
      - images:/app/wwwroot/media
    environment:
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=bonsai;User Id=bonsai;Password=test;Persist Security Info=true
      - ElasticSearch__Host=http://elastic:9200
      - Auth__Facebook__AppId=
      - Auth__Facebook__AppSecret=
      - Auth__Google__ClientId=
      - Auth__Google__ClientSecret=
      - Auth__Yandex__ClientId=
      - Auth__Yandex__ClientSecret=
      - Auth__Vkontakte__ClientId=
      - Auth__Vkontakte__ClientSecret=
      - WebServer__RequireHttps=false
      - ASPNETCORE_ENVIRONMENT=Production
    labels: 
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host: @@YOUR_IP@@.xip.io"
    stop_signal: SIGKILL
    links:
      - postgres
      - elastic

  postgres:
    image: postgres
    restart: unless-stopped
    labels: 
      - "traefik.enable=false"
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: bonsai
      POSTGRES_DB: bonsai

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    labels: 
      - "traefik.enable=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    entrypoint: >
      bash -c "
      [ -x /usr/share/elasticsearch/plugins/analysis-morphology ] || bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.14/elasticsearch-analysis-morphology-5.6.14.zip
      && bin/es-docker"

volumes:
  database: {}
  elastic: {}
  images: {}
